-- AlterTable
ALTER TABLE "AboutContent" DROP COLUMN "storyBodyEn",
DROP COLUMN "storyBodyVi",
DROP COLUMN "storyImage",
ADD COLUMN     "missionGoals" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "missionImage" TEXT,
ADD COLUMN     "missionImageCaptionEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "missionImageCaptionVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "missionIntroEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "missionIntroVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "promiseClosingEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "promiseClosingVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "promiseHeadingEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "promiseHeadingVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "promiseLines" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "storySections" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "storySubheadingEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "storySubheadingVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "visionPoints" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "visionSubtitleEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "visionSubtitleVi" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "visionTaglineEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "visionTaglineVi" TEXT NOT NULL DEFAULT '';

